//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streaming.Data
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Defines an Artist
    /// </summary>
    public partial class artist
    {
        /// <summary>
        /// Constructor of the artist which sets the list of songs to a new HashSet of song objects
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]        
        public artist()
        {
            this.songs = new HashSet<song>();
        }
        /// <summary>
        /// Properties for the artist_id of the artist
        /// </summary>
        public int artist_id { get; set; }
        /// <summary>
        /// Properties for the artist_name of the artist
        /// </summary>
        public string artist_name { get; set; }
        /// <summary>
        /// Properties for the artist_label of the artist
        /// </summary>
        public string artist_label { get; set; }
        /// <summary>
        /// Properties for the artist_age of the artist
        /// </summary>
        public Nullable<int> artist_age { get; set; }
        /// <summary>
        /// Properties for the artist_gender of the artist
        /// </summary>
        public string artist_gender { get; set; }
        /// <summary>
        /// Properties for the artist_genre of the artist
        /// </summary>
        public string artist_genre { get; set; }

        /// <summary>
        /// Collection of the artists songs
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<song> songs { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            return $"Artist ID: {artist_id}, Artist Name: {artist_name}, Artist Label: {artist_label}, Artist Age: {artist_age}" +
                $" Artist Gender: {artist_gender}, Artist Genre: {artist_genre}";
        }
    }
}
