//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streaming.Data
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Class which defines a conn_listener_song element
    /// </summary>
    public partial class conn_listener_song
    {
        /// <summary>
        /// Properties for the connTwo_id of a conn_listener_song
        /// </summary>
        public int connTwo_id { get; set; }
        /// <summary>
        /// Properties for the connTwo_listenerId of a conn_listener_song
        /// </summary>
        public Nullable<int> connTwo_listenerId { get; set; }
        /// <summary>
        /// Properties for the connTwo_songId of a conn_listener_song
        /// </summary>
        public Nullable<int> connTwo_songId { get; set; }

        /// <summary>
        /// Properties for the listener of a conn_listener_song
        /// </summary>
        public virtual listener listener { get; set; }
        /// <summary>
        /// Properties for the song of a conn_listener_song
        /// </summary>
        public virtual song song { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            return $"ID: {connTwo_id}, Listener ID: {connTwo_listenerId}, Song ID: {connTwo_songId}";
        }
    }

}
