//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streaming.Data
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Class which defines a conn_song_service element
    /// </summary>
    public partial class conn_song_service
    {
        /// <summary>
        /// Properties for the connOne__id of a conn_song_service
        /// </summary>
        public int connOne__id { get; set; }
        /// <summary>
        /// Properties for the connOne__songId of a conn_song_service
        /// </summary>
        public Nullable<int> connOne_songId { get; set; }
        /// <summary>
        /// Properties for the connOne__serviceId of a conn_song_service
        /// </summary>
        public Nullable<int> connOne_serviceId { get; set; }

        /// <summary>
        /// Properties for the song of a conn_song_service
        /// </summary>
        public virtual song song { get; set; }
        /// <summary>
        /// Properties for the service of a conn_song_service
        /// </summary>
        public virtual serv serv { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            return $"ID: {connOne__id}, Song ID: {connOne_songId}, Service ID: {connOne_serviceId}";
        }
    }
}
