//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streaming.Data
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Class which defines a serv element
    /// </summary>
    public partial class serv
    {
        /// <summary>
        /// Constructor of the serv which sets the list of conn_song_service to a new HashSet of conn_song_service objects
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public serv()
        {
            this.conn_song_service = new HashSet<conn_song_service>();
        }

        /// <summary>
        /// Properties for the serv_id of the serv
        /// </summary>
        public int serv_id { get; set; }
        /// <summary>
        /// Properties for the serv_name of the serv
        /// </summary>
        public string serv_name { get; set; }
        /// <summary>
        /// Properties for the serv_size of the serv
        /// </summary>
        public Nullable<int> serv_size { get; set; }
        /// <summary>
        /// Properties for the serv_website of the serv
        /// </summary>
        public string serv_website { get; set; }
        /// <summary>
        /// Properties for the serv_price of the serv
        /// </summary>
        public Nullable<int> serv_price { get; set; }
        /// <summary>
        /// Properties for the serv_country of the serv
        /// </summary>
        public string serv_country { get; set; }

        /// <summary>
        /// Properties for the conn_song_serv of the serv  
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conn_song_service> conn_song_service { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            return $"Service ID: {serv_id}, Service Name: {serv_name}, Number of users: {serv_size} million, Website: {serv_website}," +
                $" Price per month: {serv_price}, Country of Origin: {serv_country}";
        }
    }
}
