//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streaming.Data
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Class which defines a song element
    /// </summary>
    public partial class song
    {
        /// <summary>
        /// Constructor of the song which sets the list of conn_song_service to a new HashSet of conn_song_service objects, 
        /// and sets the list of conn_listener_song to a new HashSet of conn_listener_song objects
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public song()
        {
            this.conn_listener_song = new HashSet<conn_listener_song>();
            this.conn_song_service = new HashSet<conn_song_service>();
        }

        /// <summary>
        /// Properties for the song_id of the song
        /// </summary>
        public int song_id { get; set; }
        /// <summary>
        /// Properties for the song_title of the song
        /// </summary>
        public string song_title { get; set; }
        /// <summary>
        /// Properties for the song_album of the song
        /// </summary>
        public string song_album { get; set; }
        /// <summary>
        /// Properties for the song_length of the song
        /// </summary>
        public Nullable<int> song_length { get; set; }
        /// <summary>
        /// Properties for the song_explicit of the song
        /// </summary>
        public Nullable<bool> song_explicit { get; set; }
        /// <summary>
        /// Properties for the song_dateRealesed of the song
        /// </summary>
        public Nullable<System.DateTime> song_dateReleased { get; set; }
        /// <summary>
        /// Properties for the song_artistId foreign key of the song
        /// </summary>
        public Nullable<int> song_artistId { get; set; }

        /// <summary>
        /// Properties for the artist of the song based on the foreign key
        /// </summary>
        public virtual artist artist { get; set; }
        /// <summary>
        /// Properties for the conn_listener_song of the song
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conn_listener_song> conn_listener_song { get; set; }
        /// <summary>
        /// Properties for the conn_song_service of the song
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conn_song_service> conn_song_service { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            return $"Song ID: {song_id}, Song title: {song_title}, Song album: {song_album}, Song length (seconds): {song_length}" +
                $" Explicit: {song_explicit}, Date Released: {song_dateReleased}, Artist: {song_artistId}";
        }
    }
}
