//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streaming.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    /// <summary>
    /// StreamingDatabaseEntities class
    /// </summary>
    public partial class StreamingDatabaseEntities : DbContext
    {

        /// <summary>
        /// Instantiates a new StreamingDatabaseEntities instance
        /// </summary>
        public StreamingDatabaseEntities()
            : base("name=StreamingDatabaseEntities")
        {
        }
    
        /// <summary>
        /// OnModelCreating method that throws an exception
        /// </summary>
        /// <param name="modelBuilder">takes a DbModelBuiler as a parameter</param>
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        /// <summary>
        /// Gets and sets DbSet artist
        /// </summary>
        public virtual DbSet<artist> artists { get; set; }
        /// <summary>
        /// Gets and sets DbSet conn_listener_song
        /// </summary>
        public virtual DbSet<conn_listener_song> conn_listener_song { get; set; }
        /// <summary>
        /// Gets and sets DbSet conn_song_service
        /// </summary>
        public virtual DbSet<conn_song_service> conn_song_service { get; set; }
        /// <summary>
        /// Gets and sets DbSet listener
        /// </summary>
        public virtual DbSet<listener> listeners { get; set; }
        /// <summary>
        /// Gets and sets DbSet servs
        /// </summary>
        public virtual DbSet<serv> servs { get; set; }
        /// <summary>
        /// Gets and sets DbSet songs
        /// </summary>
        public virtual DbSet<song> songs { get; set; }
    }
}
